[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       spring_json
    Reserve_Data On

[OUTPUT]
    Name         es
    Match        *
    Host         elasticsearch
    Port         9200
    Index        service-logs
    Suppress_Type_Name    On