spring.application.name=service-foo

spring.datasource.url=jdbc:postgresql://localhost:5432/service_foo
spring.datasource.username=service_foo
spring.datasource.password=service_foo

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.group.readiness.include=readinessState,db
management.endpoint.health.show-details=always
