name: CI - Libraries

on:
    push:
        branches:
            - main
        paths:
            - 'libs/**'
            - '.github/workflows/libs-*.yml'
            - '.github/workflows/scripts/shared/**'
            - '.github/workflows/scripts/libs/**'
    pull_request:
        branches:
            - main
        paths:
            - 'libs/**'
            - '.github/workflows/libs-*.yml'
            - '.github/workflows/scripts/shared/**'
            - '.github/workflows/scripts/libs/**'
    workflow_dispatch:

jobs:
    verify-lib-foo:
      uses: ./.github/workflows/lib-foo-verify-ci.yml
        