name: Test CI

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Test bash script
              shell: bash
              run: |
                ./.github/workflows/scripts/detect_changed_projects.sh
